package com.quickcache.server.protocol;

public enum ProtocolCommand {
	REGISTER,
	REGISTER_FOR_SERVER_PUSH,
	HANDSHAKE_COMPLETE,
	RESPONSE_FROM_CLIENT,
	GET_STRING,
	SET_STRING,
	GET_MAP_VALUE,
	GET_MAP_FIELDS,
	GET_MAP_FIELD_VALUES,
	SET_MAP_VALUE;
}
